org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

systemProp.http.proxyHost=21.0.0.133
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_01NxJiyrw2uFphUDWKqcD3LP--claude_code_remote--48c809
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjgwMThiYzg2LTYwMGEtNDI1OS1iYmU5LWNhZTA3NWE3Y2EyMCIsImlhdCI6MTc3MTQxNjkxMCwiZXhwIjoxNzcxNDMxMzEwLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMU0yUEdGTXh5UWtXa290U0JQUmI0Y0EiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFOeEppeXJ3MnVGcGhVRFdLcWNEM0xQLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTQ4YzgwOSJ9.YkiaeDtRlieCJZpnOehnqJgrwxewrUgd5t9JwrBWwUdgplgLuj-YBSjacZtD54hHvl4RCxbLyLjGYnJoouMLHA
systemProp.https.proxyHost=21.0.0.133
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_01NxJiyrw2uFphUDWKqcD3LP--claude_code_remote--48c809
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6IjgwMThiYzg2LTYwMGEtNDI1OS1iYmU5LWNhZTA3NWE3Y2EyMCIsImlhdCI6MTc3MTQxNjkxMCwiZXhwIjoxNzcxNDMxMzEwLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMU0yUEdGTXh5UWtXa290U0JQUmI0Y0EiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFOeEppeXJ3MnVGcGhVRFdLcWNEM0xQLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTQ4YzgwOSJ9.YkiaeDtRlieCJZpnOehnqJgrwxewrUgd5t9JwrBWwUdgplgLuj-YBSjacZtD54hHvl4RCxbLyLjGYnJoouMLHA
systemProp.http.nonProxyHosts=localhost|127.0.0.1
